#!/bin/bash

# Automated DNS Setup Helper
# Note: You must manually execute these commands/changes in your DNS provider

echo "========================================="
echo "DNS Setup Helper"
echo "Domain: sp-wiki.octol.ink"
echo "Target: dev-jelly.github.io"
echo "========================================="
echo ""

echo "IMPORTANT: This script cannot configure DNS automatically."
echo "You must manually add the DNS record at your DNS provider."
echo ""

echo "========================================="
echo "DNS Configuration Details"
echo "========================================="
echo ""

echo "Record Type: CNAME"
echo "Name/Host: sp-wiki"
echo "Value/Target: dev-jelly.github.io"
echo "TTL: 3600 (1 hour) or Auto"
echo ""

echo "========================================="
echo "DNS Provider Setup Instructions"
echo "========================================="
echo ""

echo "Choose your DNS provider:"
echo ""
echo "1) Cloudflare"
echo "2) Namecheap"
echo "3) GoDaddy"
echo "4) Google Domains"
echo "5) Other"
echo ""

read -p "Enter choice (1-5): " PROVIDER

case $PROVIDER in
    1)
        echo ""
        echo "=== Cloudflare Setup ==="
        echo ""
        echo "1. Go to: https://dash.cloudflare.com"
        echo "2. Select 'octol.ink' domain"
        echo "3. Click 'DNS' → 'Records'"
        echo "4. Click 'Add Record'"
        echo "5. Fill in:"
        echo "   - Type: CNAME"
        echo "   - Name: sp-wiki"
        echo "   - Target: dev-jelly.github.io"
        echo "   - Proxy status: DNS only (gray) or Proxied (orange)"
        echo "   - TTL: Auto"
        echo "6. Click 'Save'"
        echo ""
        echo "Direct link: https://dash.cloudflare.com"
        ;;
    2)
        echo ""
        echo "=== Namecheap Setup ==="
        echo ""
        echo "1. Go to: https://ap.www.namecheap.com"
        echo "2. Log in to your account"
        echo "3. Click 'Domain List' → 'Manage' next to octol.ink"
        echo "4. Click 'Advanced DNS' tab"
        echo "5. Click 'Add New Record'"
        echo "6. Fill in:"
        echo "   - Type: CNAME Record"
        echo "   - Host: sp-wiki"
        echo "   - Value: dev-jelly.github.io"
        echo "   - TTL: Automatic"
        echo "7. Click 'Save All Changes'"
        echo ""
        echo "Direct link: https://ap.www.namecheap.com"
        ;;
    3)
        echo ""
        echo "=== GoDaddy Setup ==="
        echo ""
        echo "1. Go to: https://dcc.godaddy.com/manage/dns"
        echo "2. Select 'octol.ink' domain"
        echo "3. Click 'Add' button"
        echo "4. Fill in:"
        echo "   - Type: CNAME"
        echo "   - Name/Host: @sp-wiki"
        echo "   - Value/Points to: dev-jelly.github.io"
        echo "   - TTL: 1 Hour"
        echo "5. Click 'Save'"
        echo ""
        echo "Direct link: https://dcc.godaddy.com/manage/dns"
        ;;
    4)
        echo ""
        echo "=== Google Domains Setup ==="
        echo ""
        echo "1. Go to: https://domains.google.com"
        echo "2. Select 'octol.ink' domain"
        echo "3. Click 'DNS' on left sidebar"
        echo "4. Scroll to 'Custom resource records'"
        echo "5. Click 'Create custom record'"
        echo "6. Fill in:"
        echo "   - Name: sp-wiki"
        echo "   - Type: CNAME"
        echo "   - TTL: 3600"
        echo "   - Data: dev-jelly.github.io"
        echo "7. Click 'Add'"
        echo ""
        echo "Direct link: https://domains.google.com"
        ;;
    5)
        echo ""
        echo "=== Generic DNS Setup ==="
        echo ""
        echo "1. Log in to your DNS provider's control panel"
        echo "2. Navigate to DNS management for 'octol.ink'"
        echo "3. Add new CNAME record:"
        echo "   - Type/Record Type: CNAME"
        echo "   - Name/Host: sp-wiki"
        echo "   - Value/Target/Points to: dev-jelly.github.io"
        echo "   - TTL: 3600 or Auto"
        echo "4. Save changes"
        echo ""
        echo "Don't know your DNS provider?"
        echo "Check: https://www.whois.com/whois/octol.ink"
        echo ""
        ;;
    *)
        echo ""
        echo "Invalid choice. Please try again."
        exit 1
        ;;
esac

echo ""
echo "========================================="
echo "After Adding DNS Record"
echo "========================================="
echo ""

echo "1. Wait for DNS propagation (5 min - 24 hours)"
echo ""
echo "2. Verify DNS configuration:"
echo "   Run: bash scripts/verify-dns.sh"
echo ""
echo "3. Test site access:"
echo "   Open: https://sp-wiki.octol.ink"
echo ""

echo "========================================="
echo "Troubleshooting"
echo "========================================="
echo ""

echo "DNS not resolving after 24 hours?"
echo "- Check CNAME record is correct (sp-wiki → dev-jelly.github.io)"
echo "- Verify TTL is set appropriately"
echo "- Check for typos in domain or target"
echo ""
echo "Site still not accessible?"
echo "- Clear browser cache"
echo "- Try different browser or device"
echo "- Run: bash scripts/verify-dns.sh"
echo ""
echo "For detailed help: See DNS_SETUP.md"
echo ""

echo "========================================="
echo "Summary"
echo "========================================="
echo ""
echo "CNAME Record to Add:"
echo "  Name: sp-wiki"
echo "  Type: CNAME"
echo "  Value: dev-jelly.github.io"
echo "  TTL: 3600 or Auto"
echo ""
echo "After setup, run: bash scripts/verify-dns.sh"
echo "========================================="
